name: Documents Validation

on:
  pull_request:
    branches:
      - main

jobs:
  link_check:
    name: Link Checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v1.4.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: --exclude-mail --accept=401 --no-progress 'docs/**/*.md'
          fail: false
